-- ============================================================
-- FrameConfig — live-update handlers for unitConfigs.*
-- Split into sub-modules:
--   FrameConfigShared.lua   — shared infrastructure
--   FrameConfigLayout.lua   — position, dimensions, group layout
--   FrameConfigElements.lua — power, portrait, castbar, status icons
--   FrameConfigHealth.lua   — health coloring, shields, absorbs
--   FrameConfigText.lua     — text formatting, fonts, anchors
--   FrameConfigPreset.lua   — preset change handler
--   FrameConfigPets.lua     — party pets handler
-- ============================================================
